spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skoltech-test
    username: postgres
    password: pass
    initialization-mode: always

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  profiles:
    active: dev

logging:
  level:
    ROOT: INFO
    ru.demi.auction: DEBUG
    org.springframework: DEBUG
    org.springframework.orm: WARN
    org.hibernate: DEBUG
#    org.hibernate.SQL: WARN
#    org.hibernate.type.descriptor.sql.BasicBinder: WARN


