version: '2'
services:
  app:
    image: skoltech-test:1.0
    network_mode: 'host'
    ports:
     - '8080:8080'
    environment:
      - POSTGRES_PASSWORD=p@ss
      - POSTGRES_URL=jdbc:postgresql://127.0.0.1:5432/skoltechtest
      - POSTGRES_USER=postgres
    depends_on:
      - mypostgres
    volumes:
      - ../_tmp_data:/var/lib/postgresql/data
  mypostgres:
    image: postgres:9.6
    network_mode: 'host'
    ports:
     - '5432:5432'
    environment:
     - POSTGRES_PASSWORD=p@ss
     - POSTGRES_USER=postgres
     - POSTGRES_DB=skoltechtest
